name: Build

on: 
  push:

jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Create necessary directories
        run: mkdir -p obj/filetest
      - name: Check codestyle
        run: |
          echo "Check codestyle..."
          git ls-files '*.cpp' '*.h' | xargs clang-format -i --verbose && git diff --exit-code
          echo "Codestyle is fine."

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Create necessary directories
        run: mkdir -p obj/filetest
      - name: Compile the code
        run: |
          echo "Compiling the code..."
          make
          echo "Compile complete."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Create necessary directories
        run: mkdir -p obj/filetest
      - name: Run tests
        run: |
          echo "Running tests..."
          make test
          echo "Tests complete."
